import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import { MantineProvider, createTheme } from "@mantine/core";
import "@mantine/core/styles.css";

const theme = createTheme({});

const averta = localfont({
  src: [
    {
      path: "../../public/assets/fonts/AvertaStd-Regular-ca60f1dfe676a0b2f185812af147c08792cf392db5dcecdf5967b92914fc7c39.ttf",
    },
  ],
  variable: "--font-averta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${averta.variable} overflow-x-hidden overflow-y-scroll bg-[#FAFAFA] font-averta`}
      >
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
